web:
  image: workshop/nginx
  ports:
    - "8080:80"
  volumes:
    - ./:/var/www
    - ./images/nginx/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./:/app
    - ./images/php-fpm/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
